// Integracion de funciones de pedidos, gastos, cigarros y cajillas
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class FeatureProduct{final String name;final int packSize;const FeatureProduct(this.name,this.packSize);}
class FeatureDaySummary{final int expensesTotal,ordersPaid,cigaretteSales;const FeatureDaySummary({required this.expensesTotal,required this.ordersPaid,required this.cigaretteSales});}
class FeatureStore{
 static Future<SharedPreferences> get _p=>SharedPreferences.getInstance();
 static Future<List<Map<String,dynamic>>> _list(String key)async{final p=await _p;final raw=p.getString(key);if(raw==null)return [];try{return List<Map<String,dynamic>>.from((jsonDecode(raw) as List).map((e)=>Map<String,dynamic>.from(e)));}catch(_){return [];}}
 static Future<void> _save(String key,List<Map<String,dynamic>> v)async=>(await _p).setString(key,jsonEncode(v));
 static Future<FeatureDaySummary> summary()async{final expenses=await _list('feature_expenses'),orders=await _list('feature_orders'),cigs=await _list('feature_cigarettes');final p=await _p;final er=jsonDecode(p.getString('feature_cigarette_entries')??'{}');final or=jsonDecode(p.getString('feature_cigarette_opening')??'{}');final entries=Map<String,dynamic>.from(er);final opening=Map<String,dynamic>.from(or);int cigSales=0;for(final c in cigs){final name=c['name'];final sold=(int.tryParse('${opening[name]??c['stock']}')??0)+(int.tryParse('${entries[name]??0}')??0)-(int.tryParse('${c['stock']??0}')??0);cigSales+=sold*(int.tryParse('${c['price']??0}')??0);}return FeatureDaySummary(expensesTotal:expenses.fold(0,(s,e)=>s+(int.tryParse('${e['amount']??0}')??0)),ordersPaid:orders.fold(0,(s,e)=>s+(int.tryParse('${e['paid']??0}')??0)),cigaretteSales:cigSales);}
 static Future<void> resetDay()async{final p=await _p;await _save('feature_expenses',[]);await _save('feature_orders',[]);final cigs=await _list('feature_cigarettes');final opening=<String,int>{for(final c in cigs)c['name']:(int.tryParse('${c['stock']??0}')??0)};await p.setString('feature_cigarette_entries',jsonEncode(<String,int>{}));await p.setString('feature_cigarette_opening',jsonEncode(opening));}
}
class FeatureHubPage extends StatefulWidget{final List<FeatureProduct> products;final void Function(String,int) onWarehouseAdd;final VoidCallback onChanged;const FeatureHubPage({super.key,required this.products,required this.onWarehouseAdd,required this.onChanged});@override State<FeatureHubPage> createState()=>_FeatureHubState();}
class _FeatureHubState extends State<FeatureHubPage>{
 int tab=0;bool loading=true;List<Map<String,dynamic>> expenses=[],orders=[],cigs=[];Map<String,int> entries={},opening={};
 @override void initState(){super.initState();load();}
 Future<void> load()async{expenses=await FeatureStore._list('feature_expenses');orders=await FeatureStore._list('feature_orders');cigs=await FeatureStore._list('feature_cigarettes');final p=await FeatureStore._p;final a=jsonDecode(p.getString('feature_cigarette_entries')??'{}');final o=jsonDecode(p.getString('feature_cigarette_opening')??'{}');entries=Map<String,int>.from((a as Map).map((k,v)=>MapEntry(k,(v as num).toInt())));opening=Map<String,int>.from((o as Map).map((k,v)=>MapEntry(k,(v as num).toInt())));if(cigs.isEmpty){cigs=[{'name':'Cigarros','price':0,'stock':0}];await save();}setState(()=>loading=false);}
 Future<void> save()async{await FeatureStore._save('feature_expenses',expenses);await FeatureStore._save('feature_orders',orders);await FeatureStore._save('feature_cigarettes',cigs);final p=await FeatureStore._p;await p.setString('feature_cigarette_entries',jsonEncode(entries));await p.setString('feature_cigarette_opening',jsonEncode(opening));}
 Future<void> addExpense()async{final concept=TextEditingController(),amount=TextEditingController(),obs=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Registrar gasto'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:concept,decoration:const InputDecoration(labelText:'Concepto')),TextField(controller:amount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Monto C\$')),TextField(controller:obs,decoration:const InputDecoration(labelText:'Observación'))]),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Guardar'))]));if(ok==true&&(int.tryParse(amount.text)??0)>0&&concept.text.trim().isNotEmpty){expenses.add({'concept':concept.text.trim(),'amount':int.parse(amount.text),'observation':obs.text.trim(),'date':DateTime.now().toIso8601String()});await save();setState((){});widget.onChanged();}concept.dispose();amount.dispose();obs.dispose();}
 Future<void> addOrder()async{final supplier=TextEditingController(),paid=TextEditingController(),obs=TextEditingController();final cases={for(final p in widget.products)p.name:TextEditingController(text:'0')};final cigUnits={for(final c in cigs)c['name']:TextEditingController(text:'0')};final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Registrar pedido'),content:SizedBox(width:500,child:SingleChildScrollView(child:Column(children:[TextField(controller:supplier,decoration:const InputDecoration(labelText:'Proveedor')),const SizedBox(height:8),...widget.products.map((p)=>TextField(controller:cases[p.name],keyboardType:TextInputType.number,decoration:InputDecoration(labelText:'${p.name} — cajillas (${p.packSize} unidades)'))),const Divider(),const Text('Cigarros',style:TextStyle(fontWeight:FontWeight.bold)),...cigs.map((c)=>TextField(controller:cigUnits[c['name']],keyboardType:TextInputType.number,decoration:InputDecoration(labelText:'Unidades de ${c['name']}'))),TextField(controller:paid,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Total pagado C\$')),TextField(controller:obs,decoration:const InputDecoration(labelText:'Observación'))])),),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Guardar'))]));if(ok==true){final wc=<String,int>{};for(final p in widget.products){final n=int.tryParse(cases[p.name]!.text)??0;if(n>0){wc[p.name]=n;widget.onWarehouseAdd(p.name,n*p.packSize);}}for(final c in cigs){final n=int.tryParse(cigUnits[c['name']]!.text)??0;if(n>0){c['stock']=(c['stock'] as int)+n;entries[c['name']]=(entries[c['name']]??0)+n;}}orders.add({'supplier':supplier.text.trim(),'paid':int.tryParse(paid.text)??0,'cases':wc,'date':DateTime.now().toIso8601String(),'observation':obs.text.trim()});await save();setState((){});widget.onChanged();}for(final c in cases.values)c.dispose();for(final c in cigUnits.values)c.dispose();supplier.dispose();paid.dispose();obs.dispose();}
 Future<void> addCigarette()async{final name=TextEditingController(),price=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Nuevo producto de cigarros'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:name,decoration:const InputDecoration(labelText:'Nombre')),TextField(controller:price,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Precio de venta C\$'))]),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Guardar'))]));if(ok==true&&name.text.trim().isNotEmpty){cigs.add({'name':name.text.trim(),'price':int.tryParse(price.text)??0,'stock':0});opening[name.text.trim()]=0;entries[name.text.trim()]=0;await save();setState((){});}name.dispose();price.dispose();}
 Widget expensesTab()=>ListView(padding:const EdgeInsets.all(16),children:[FilledButton.icon(onPressed:addExpense,icon:const Icon(Icons.add),label:const Text('Registrar gasto')),const SizedBox(height:12),...expenses.reversed.map((e)=>Card(child:ListTile(title:Text(e['concept']??''),subtitle:Text(e['observation']??''),trailing:Text('C\$${e['amount']}')))),if(expenses.isEmpty)const Text('No hay gastos registrados.')]);
 Widget ordersTab()=>ListView(padding:const EdgeInsets.all(16),children:[FilledButton.icon(onPressed:addOrder,icon:const Icon(Icons.add_shopping_cart),label:const Text('Registrar pedido')),const SizedBox(height:12),...orders.reversed.map((o)=>Card(child:ListTile(title:Text((o['supplier']??'').toString().isEmpty?'Pedido':'Pedido — ${o['supplier']}'),subtitle:Text('Pagado C\$${o['paid']}'),trailing:const Icon(Icons.receipt_long)))),if(orders.isEmpty)const Text('No hay pedidos registrados.')]);
 Widget cigTab()=>ListView(padding:const EdgeInsets.all(16),children:[FilledButton.icon(onPressed:addCigarette,icon:const Icon(Icons.add),label:const Text('Agregar producto de cigarros')),const SizedBox(height:12),...cigs.map((c)=>Card(child:ListTile(title:Text(c['name']),subtitle:Text('Existencia: ${c['stock']} • Inicial: ${opening[c['name']]??c['stock']} • Entradas: ${entries[c['name']]??0}'),trailing:Text('C\$${c['price']}'))))]);
 @override Widget build(BuildContext context){if(loading)return const Scaffold(body:Center(child:CircularProgressIndicator()));final pages=[ordersTab(),expensesTab(),cigTab()];return Scaffold(appBar:AppBar(title:const Text('Pedidos, gastos y cigarros')),body:pages[tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.inventory_2),label:'Pedidos'),NavigationDestination(icon:Icon(Icons.money_off),label:'Gastos'),NavigationDestination(icon:Icon(Icons.smoking_rooms),label:'Cigarros')]));}
}
